package com.jinproject.domain.model

enum class Stat(val displayName: String, val displayOtherLanguage: String) {
    HP(displayName = "체력", displayOtherLanguage = "Hp"),
    MP(displayName = "마나", displayOtherLanguage = "Mp"),
    HPPER(displayName = "체력%", displayOtherLanguage = "Hp%"),
    MPPER(displayName = "마나%", displayOtherLanguage = "Mp%"),
    HPREGEN(displayName = "체력재생", displayOtherLanguage = "HpRegen"),
    MPREGEN(displayName = "마나재생", displayOtherLanguage = "MpRegen"),
    HR(displayName = "명중", displayOtherLanguage = "Hr"),
    CRI(displayName = "크리티컬", displayOtherLanguage = "Cri"),
    STATINT(displayName = "지능", displayOtherLanguage = "Int"),
    STATSTR(displayName = "힘", displayOtherLanguage = "Str"),
    STATDEX(displayName = "민첩", displayOtherLanguage = "Dex"),
    MOVE(displayName = "이동속도", displayOtherLanguage = "Speed"),
    ARMOR(displayName = "방어력", displayOtherLanguage = "Armor"),
    PVEDMG(displayName = "pve데미지증가", displayOtherLanguage = "PveDmgUp"),
    PVPDMG(displayName = "pvp데미지증가", displayOtherLanguage = "PvpDmgUp"),
    PVEDMGPER(displayName = "pve데미지증가%", displayOtherLanguage = "PveDmgUp%"),
    PVPDMGPER(displayName = "pvp데미지증가%", displayOtherLanguage = "PvpDmgUp%"),
    PVEDMGDOWN(displayName = "pve데미지감소", displayOtherLanguage = "PveDmgDown"),
    PVPDMGDOWN(displayName = "pvp데미지감소", displayOtherLanguage = "PvpDmgDown"),
    PVEDMGDOWNPER(displayName = "pve데미지감소%", displayOtherLanguage = "PveDmgDown%"),
    PVPDMGDOWNPER(displayName = "pvp데미지감소%", displayOtherLanguage = "PvpDmgDown%"),
    GOLDDROP(displayName = "골드드랍률", displayOtherLanguage = "GoldDrop"),
    ITEMDROP(displayName = "아이템드랍률", displayOtherLanguage = "ItemDrop"),
    BOSSDMGPER(displayName = "보스데미지%", displayOtherLanguage = "BossDmg%"),
    CRITDMGDOWN(displayName = "크리티컬데미지감소", displayOtherLanguage = "CriDmgDown"),
    CRITDMGDOWNPER(displayName = "크리티컬데미지감소%", displayOtherLanguage = "CriDmgDown%"),
    MISS(displayName = "회피", displayOtherLanguage = "Avoidance"),
    CRITRESISTPER(displayName = "크리티컬저항%", displayOtherLanguage = "CritResist%")
}