name: test
on: 
  push:
    branches: 
           - test
jobs:
  extract_version:
    runs-on: ubuntu-latest
    outputs:
      version_name: ${{ steps.extract_version.outputs.version_name }}

    steps:
    - name: Checkout Repository
      uses: actions/checkout@v4

    - name: Extract Version Name
      id: extract_version
      run: |
         VERSION=$(git log -1 --pretty=%B | grep -oP 'test:\s*\K[0-9]+\.[0-9]+\.[0-9]+' || echo "unknown")
         VERSION=${VERSION:-"unknown"}
         echo "Extracted version: $VERSION"
         {
           echo "version_name<<EOF"
           echo "$VERSION"
           echo "EOF"
         } >> "$GITHUB_OUTPUT"
      

  build:
    runs-on: ubuntu-latest
    needs: extract_version
    if: ${{ needs.extract_version.outputs.version_name != 'unknown' }}
    steps:
    
    - uses: actions/checkout@v4
    
    - name: set up JDK 17
      uses: actions/setup-java@v4
      with:
        java-version: '17'
        distribution: 'temurin'
        cache: gradle
      
    - name: Grant execute permission for gradlew
      run: chmod +x ./gradlew

    - name: Create Local Properties
      run: echo '${{ secrets.LOCAL_PROPERTIES }}' >> ./local.properties
      
    - name: Create google-services
      run: echo '${{ secrets.GOOGLE_SERVICES_JSON_DEBUG }}' > ./app/google-services.json

    - name: Debug App Bundle
      run: ./gradlew assembleDebug -Duser.language=ko -Duser.country=KR

    - name: Send artifact to slack channel
      uses: slackapi/slack-github-action@v2.1.1
      with:
        method: files.uploadV2
        token: ${{ secrets.SLACK_BOT_OAUTH }}
        payload: |
          channel_id: ${{ secrets.SLACK_CHANNEL_ID }}
          initial_comment: "test"
          file: "app/build/outputs/apk/debug/app-debug.apk"
          filename: "app-debug.apk"
          fileType: "apk"